-- MySQL Script generated by MySQL Workbench
-- Mon Mar 29 08:09:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_nome_minha_casa_mais_bonita
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_nome_minha_casa_mais_bonita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_nome_minha_casa_mais_bonita` DEFAULT CHARACTER SET utf8 ;
USE `db_nome_minha_casa_mais_bonita` ;

-- -----------------------------------------------------
-- Table `db_nome_minha_casa_mais_bonita`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nome_minha_casa_mais_bonita`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `tipo_produto` VARCHAR(45) NOT NULL,
  `peso` INT NOT NULL,
  `sabor` VARCHAR(45) NOT NULL,
  `embalagem` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_produto`),
  UNIQUE INDEX `id_produto_UNIQUE` (`id_produto` ASC) VISIBLE,
  UNIQUE INDEX `tipo_produto_UNIQUE` (`tipo_produto` ASC) VISIBLE,
  UNIQUE INDEX `marca_produto_UNIQUE` (`sabor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nome_minha_casa_mais_bonita`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nome_minha_casa_mais_bonita`.`tb_categoria` (
  `id_categoria` INT NOT NULL,
  `preço` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `fk_id_produto` INT NOT NULL,
  PRIMARY KEY (`id_categoria`),
  INDEX `fk_tb_categoria_tb_produto_idx` (`fk_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_categoria_tb_produto`
    FOREIGN KEY (`fk_id_produto`)
    REFERENCES `db_nome_minha_casa_mais_bonita`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nome_minha_casa_mais_bonita`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nome_minha_casa_mais_bonita`.`tb_usuario` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` INT NOT NULL,
  `telefone` INT NULL,
  `email` VARCHAR(45) NULL,
  `fk_id_produto` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_tb_usuario_tb_produto1_idx` (`fk_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_tb_produto1`
    FOREIGN KEY (`fk_id_produto`)
    REFERENCES `db_nome_minha_casa_mais_bonita`.`tb_produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
